# Enable validating this file
version: ~> 1.0

language: python
python:
    - "3.6"

sudo: false
cache:
    directories:
        - "~/.platformio"

script:
     - platformio run

jobs:
  include:
    - install:
      - pip install -U platformio
      - platformio update
      script: platformio run
      name: "build arduino"
    - install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq libsdl2-dev
      script: ./build_simulator.sh
      name: "build simulator"
